import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

import { connectToDatabase } from "@/lib/dbConnect";
import Navbar from "./navbar/page";
import ToasterProvider from "./component/ToasterProvider";

// ✅ Connect to MongoDB once when server starts
connectToDatabase()
  .then(() => {
    console.log("✅ MongoDB connected at startup");
  })
  .catch((err) => {
    console.error("❌ MongoDB failed to connect at startup:", err);
  });
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader />
        <ToasterProvider />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
